name: Update VK Stats

on:
  schedule:
    - cron: '0 9 * * *'  # Ежедневно в 12:00 по МСК (9:00 UTC)
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Важно для истории коммитов

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run script
        env:
          VK_API_KEY: ${{ secrets.VK_API_KEY }}
        run: python main.py
        
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git diff --cached --quiet || git commit -m "Автоматическое обновление статистики"
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
